spring:
  application:
    name: userbasic

server:
  port: 9005

eureka:
  client:
    #向注册中心注册
    register-with-eureka: true
    #是否从服务端获取注册信息
    fetch-registry: true
    #从服务端获取注册信息时间间隔，默认30s
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:admin@localhost:8001/eureka/,http://admin:admin@localhost:8002/eureka/
  #    region和zone配置
  #    service-url:
  #      shanghai1: http://admin:admin@localhost:8001/eureka/
  #      shanghai2: http://admin:admin@localhost:8002/eureka/
  #    region: shanghai
  #    availability-zones:
  #      shanghai: shanghai2
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 3
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
#    zone名称
#    metadata-map:
#      zone: shanghai2

#健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info

